#!/bin/bash -x
#SBATCH --job-name="ModifyVCF"
#SBATCH --cpus-per-task=3
#SBATCH --mem=1G
#SBATCH --output=/home/mortigas/outerr/ModifyVCF_%j.out
#SBATCH --error=/home/mortigas/outerr/ModifyVCF_%j.err
#SBATCH --partition=general
#
#######MODIFY A VCF FILE#######
#This script takes a vcf file and modifies:
#the contig ID
#the chromosome id, col. 1

module load samtools/1.9

OUTPATH=/scratch/125-emmer/MartaOrtigas
DIR=/scratch/125-emmer/MartaOrtigas
HOMEPATH=/home/mortigas
OUTPUT_FILE="MODIFIED_all_emmer.biallSNP.hardfiltPASS_maxmis09.nooutl_NATChr.NOhetpositions.mac3maxmis09.rename_artChr.g.vcf"

cd $DIR
for INPUT_FILE in /projects/125-emmer/emmer_variants_durum1ref/NATChr/NO_het/all_emmer.biallSNP.hardfiltPASS_maxmis09.nooutl_NATChr.NOhetpositions.mac3maxmis09.rename.vcf.gz
do

	#1. Select the header: print in new file all lines until the contig descriptor
        zcat ${INPUT_FILE} | awk '1;/##INFO=<ID=ReadPosRankSum/{exit}' > ${OUTPATH}/${OUTPUT_FILE}

	#2. append corrected contig list and assign the length of the chromosome to a variable
        cat ${HOMEPATH}/all_emmer_artificialChr.List >> ${OUTPATH}/${OUTPUT_FILE}

	#3. change CHROM column of the vcf
    	zcat ${INPUT_FILE} | sed -n '/#CHROM/,$p'| awk -v OFS='\t' '/^#/ {print; next} {if ($1 == "1") $1 = "1A"; else if ($1 == "2") $1 = "1B"; else if ($1 == "3") $1 = "2A"; else if ($1 == "4") $1 = "2B"; else if ($1 == "5") $1 = "3A"; else if ($1 == "6") $1 = "3B"; else if ($1 == "7") $1 = "4A"; else if ($1 == "8") $1 = "4B"; else if ($1 == "9") $1 = "5A"; else if ($1 == "10") $1 = "5B"; else if ($1 == "11") $1 = "6A"; else if ($1 == "12") $1 = "6B"; else if ($1 == "13") $1 = "7A"; else if ($1 == "14") $1 = "7B"; print}' >> ${OUTPATH}/${OUTPUT_FILE}

	bgzip ${OUTPATH}/${OUTPUT_FILE}
	# we index using "csi" because the length is too long and BAI index can't handle it
	tabix --csi ${OUTPATH}/${OUTPUT_FILE}.gz

done

:<<'END'

END
module unload samtools/1.9
